In [1]:
import numpy as np
import pandas as pd

In [109]:
# load data 
df = pd.read_csv('../Resources/Auto.csv')

# remove missing values
df = df.dropna()
df = df[df.horsepower != '?']

In [126]:
# problem 5, part a
cols = list(df.columns)

In [127]:
# Problem 5, Part (b)

# name is the only qualitative predictor 
quants = cols.copy()
quants.remove('name')
data = [] 

# show range values
for col in quants: 
    values = pd.to_numeric(df[col])
    rng = max(values) - min(values)
    data.append([col, rng])

pd.DataFrame(data, columns = ['Predictor', 'Range'])

      Predictor   Range
0           mpg    37.6
1     cylinders     5.0
2  displacement   387.0
3    horsepower   184.0
4        weight  3527.0
5  acceleration    16.8
6          year    12.0
7        origin     2.0

In [128]:
# Problem 5, Part (c)

data = [] 

# show mean and SD values 
for col in quants: 
    values = pd.to_numeric(df[col])
    mean = np.mean(values)
    sd = np.std(values)
    data.append([col, mean, sd])

pd.DataFrame(data, columns = ['Predictor', 'Mean', 'St. Dev.'])

      Predictor         Mean    St. Dev.
0           mpg    23.445918    7.795046
1     cylinders     5.471939    1.703606
2  displacement   194.411990  104.510444
3    horsepower   104.469388   38.442033
4        weight  2977.584184  848.318447
5  acceleration    15.541327    2.755343
6          year    75.979592    3.679035
7        origin     1.576531    0.804490

In [129]:
# Problem 5, Part (d)

# drop last 50 obs
copy = df.copy()
copy = copy.head(-50)
data = [] 

# show new statistics in tabular format 
for col in quants:
    values = pd.to_numeric(copy[col])
    mean = np.mean(values)
    sd = np.std(values)
    rng = max(values) - min(values)
    data.append([col, rng, mean, sd])

pd.DataFrame(data, columns = ['Predictor', 'Range', 'Mean', 'St. Dev.'])

      Predictor   Range         Mean    St. Dev.
0           mpg    37.6    22.315497    7.445476
1     cylinders     5.0     5.622807    1.739078
2  displacement   387.0   203.326023  107.301495
3    horsepower   184.0   107.821637   39.641674
4        weight  3527.0  3045.578947  871.579412
5  acceleration    16.8    15.383626    2.777630
6          year    11.0    75.157895    3.191488
7        origin     2.0     1.535088    0.774368

In [ ]:
# Problem 5, Part (e)

In [ ]:
(e) Using the full data set, investigate the predictors graphically, using scatterplots
or other tools of your choice. Create some plots highlighting the relationships
among the predictors. Comment on your findings.
(f) Suppose that we wish to predict gas mileage (mpg) on the basis of the other
variables. Do your plots suggest that any of the other variables might be useful
in predicting mpg? Justify your answer.